eCert/Models/ViewModel/TranscriptViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace eCert.Models.ViewModel
{
    public class TranscriptViewModel
    {
        [CampusValidation(ErrorMessage = "Please select Campus")]
        public int CampusId { get; set; }
        [CampusValidation(ErrorMessage = "Please select Education System")]
        public int EducationSystemId { get; set; }
    }
}

eCert/Controllers/TranscriptController.cs
using eCert.Models.ViewModel;
using eCert.Services;
using eCert.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eCert.Controllers
{
    public class TranscriptController : Controller
    {
        private readonly TranscriptServices _transcriptServices;
        private readonly CertificateServices _certificateServices;
        public TranscriptController()
        {
            _transcriptServices = new TranscriptServices();
            _certificateServices = new CertificateServices();
        }
        public ActionResult LoadListTranscript(int campusId)
        {
            EducationSystemViewModel educationSystemViewModel = _transcriptServices.GetEduSystemByCampusId(campusId);
            
            List<SubjectViewModel> subjects = null;
            //campus 

            if (educationSystemViewModel.EducationName.Equals("Đại học FPT"))
            {
                string rollNumber = Session["RollNumber"].ToString();
                //Get passed subject 
                FAP_Service.UserWebServiceSoapClient client = new FAP_Service.UserWebServiceSoapClient();
                FAP_Service.Subject[] fapPassedSubject = client.GetPassedSubjects(rollNumber);
                subjects = _transcriptServices.ConvertToListSubjectViewModel(fapPassedSubject);

                foreach (SubjectViewModel subject in subjects)
                {
                    CertificateViewModel transcriptCert = _certificateServices.GetCertificateByRollNumberAndSubjectCode(rollNumber, subject.SubjectCode);
                    //Check if transcript has already generated
                    if (transcriptCert != null)
                    {
                        subject.IsGenerated = true;
                        subject.Link = "/Certificate/FPTCertificateDetail?url=" + transcriptCert.Url;
                        subject.CampusId = campusId;
                    }
                }
            }
           
            return PartialView(subjects);
        }
        // GET: Transcript
        public ActionResult ListTranscript()
        {

            if (Session["RollNumber"] != null)
            {
                if ((bool)Session["isUpdatedEmail"])
                {
                    
                    return View();
                }
                else
                {
                    //redirect to update personal email page
                    return RedirectToAction("UpdatePersonalEmail", "Authentication");
                }
            }
            else
            {
                return RedirectToAction("Index", "Authentication");
            }
            return View();

        }
        [HttpPost]
        public ActionResult ListTranscript(TranscriptViewModel transcriptViewModel)
        {
            //switch case to connect to service of education systems
            string rollNumber = Session["RollNumber"].ToString();
            //Get passed subject 
            FAP_Service.UserWebServiceSoapClient client = new FAP_Service.UserWebServiceSoapClient();
            FAP_Service.Subject[] fapPassedSubject = client.GetPassedSubjects(rollNumber);
            List<SubjectViewModel> subjects = _transcriptServices.ConvertToListSubjectViewModel(fapPassedSubject);

            foreach (SubjectViewModel subject in subjects)
            {
                CertificateViewModel transcriptCert = _certificateServices.GetCertificateByRollNumberAndSubjectCode(rollNumber, subject.SubjectCode);
                //Check if transcript has already generated
                if (transcriptCert != null)
                {
                    subject.IsGenerated = true;
                    subject.Link = "/Certificate/FPTCertificateDetail?url=" + transcriptCert.Url;
                }
            }
            EducationSystemViewModel educationSystemViewModel = _transcriptServices.GetEducationNameById(transcriptViewModel.EducationSystemId);
            CampusViewModel campusViewModel = _transcriptServices.GetCampusNameById(transcriptViewModel.CampusId);
            ViewBag.EduName = educationSystemViewModel.EducationName;
            ViewBag.CampusName = campusViewModel.CampusName;
            ViewBag.Subject = subjects;
            return View();
        }

      
        public JsonResult GenerateCertificate(string subjectCode, int campusId)
        {
            string rollNumber = Session["RollNumber"].ToString();
            SignatureViewModel signatureViewModel = _transcriptServices.GetSignatureOfPrincipalByCampusId(campusId);
            Result result = new Result();
            FAP_Service.UserWebServiceSoapClient client = new FAP_Service.UserWebServiceSoapClient();
            //Check passed subject with subject code and student rollnumber
            FAP_Service.Subject detailPassedSubject = client.GetDetailPassedSubject(rollNumber, subjectCode);
            SubjectViewModel subject = _transcriptServices.ConvertToSubjectViewModel(detailPassedSubject);
            subject.SignatureId = signatureViewModel.SignatureId;
            //Does not have that subject
            if (subject == null)
            {
                result.IsSuccess = false;
                result.Message = "Generate error.";
                //Error message
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            CertificateViewModel transcriptViewModel = _certificateServices.GetCertificateByRollNumberAndSubjectCode(rollNumber, subject.SubjectCode);
            //If regenerated
            if (transcriptViewModel != null)
            {
                //Delete old transcript certificate
                _certificateServices.DeleteCertificate(transcriptViewModel.Url);
            }
            _transcriptServices.GenerateCertificateForSubject(subject, rollNumber);
            //Message success
            result.IsSuccess = true;
            result.Message = "Generate certificate successfully.";
            return Json(result, JsonRequestBehavior.AllowGet);
        }
    }
}

eCert/Views/Transcript/ListTranscript.cshtml
@model eCert.Models.ViewModel.TranscriptViewModel
<script src="/assets/js/vendor/jquery-3.5.1.min.js"></script>
<script src="~/assets/js/custom/ListTranscript.js"></script>

<h2>Transcripts</h2>
<div class="card">
    <div class="card-body">
        
        <div class="row col-12 pr-0">
            <div class="form-group col-12 col-lg-3 pr-0 required">
                <label class="control-label">Education System: </label>
                <select class="form-control" id="EducationSystemId" name="EducationSystemId">
                    <option selected disabled>Select Education System</option>
                </select>
            </div>
            <div id="campus-select" class="form-group col-12 col-lg-3 pr-0 required">
                <label class="control-label">Campus: </label>
                <select class="form-control" id="CampusId" name="CampusId">
                    <option selected disabled>Select Campus</option>
                </select>
            </div>
            <div class="form-group col-12 col-lg-3 pr-0 required d-flex">
                <button type="button" onclick="getListTranscript()" class="btn btn-primary align-self-end" id="submitButton">Load subject</button>
            </div>
        </div>
        <div class="row col-12 pr-0">
            <div class="col-12 col-lg-3 pr-0">
                <p class="text-danger edu">Please select Education System</p>
            </div>
            <div class="col-12 col-lg-3 pr-0">
                <p class="text-danger campus">Please select Campus</p>
            </div>
        </div>
        
    <div class="listTranscript mt-2">
        @*@if (ViewBag.EduName != null && ViewBag.CampusName != null) { 
            <div class="col-12">
                <span>
                    Education System: @ViewBag.EduName
                </span>
                <span class="ml-3">
                    Campus: @ViewBag.CampusName
                </span>
            </div>
        }
        @if (ViewBag.Subject != null)
        {
            if (ViewBag.Subject.Count != 0)
            {
                <div class="table-responsive mt-2">
                    <table class="table table-centered mb-0">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Semester</th>
                                <th>Subject Code</th>
                                <th>Subject Name</th>
                                <th>Mark</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                int index = 1;
                                for (int i = 0; i < ViewBag.Subject.Count; i++)
                                {
                                    using (Html.BeginForm("GenerateCertificate", "Transcript", FormMethod.Post, new { enctype = "multipart/form-data" }))
                                    {
                                        <input type="hidden" name="subjectCode" value="@ViewBag.Subject[i].SubjectCode" />
                                        <tr>
                                            <td>@index</td>
                                            <td>@ViewBag.Subject[i].Semester</td>
                                            <td>@ViewBag.Subject[i].SubjectCode</td>
                                            <td>@ViewBag.Subject[i].SubjectName</td>
                                            <td>@ViewBag.Subject[i].Mark</td>
                                            @if (ViewBag.Subject[i].IsGenerated)
                                            {
                                                <td>
                                                    <a href="@ViewBag.Subject[i].Link">View certificate</a>
                                                </td>
                                                <td>
                                                    <button class="btn btn-primary" type="submit">Regenerate certificate</button>
                                                </td>

                                            }
                                            else
                                            {
                                                <td>
                                                    <button class="btn btn-primary" type="submit">Generate certificate</button>
                                                </td>
                                            }

                                        </tr>
                                    }

                                    index++;
                                }
                            }

                        </tbody>
                    </table>

                </div>
            }
            else
            {
                <p>There is no subject</p>
            }

        }*@

    </div>
    </div>
</div>




@Html.Partial("_AlertDialog")

@if (TempData["Msg"] != null)
{
    <script type="text/javascript">
       $(document).ready(function () {
           var data = '@TempData["Msg"]';
           $.NotificationApp.send("Message", data, "top-center", "Background color", "Icon");
          });
    </script>
}
else if (ViewBag.Msg != null)
{
    <script type="text/javascript">
       $(document).ready(function () {
           var data = '@ViewBag.Msg';
           $('#alertModal').modal('show');
           $('#confirmTitle').html('Alert');
           $('.modal-body').html(data);
          });
    </script>
}