eCert/Models/ViewModel/AddCampusViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace eCert.Models.ViewModel
{
    public class AddCampusViewModel
    {
        [CampusValidation(ErrorMessage = "Please select Education System")]
        public int EducationSystemId { get; set; }
        [Required(ErrorMessage = "Please input Campus name")]
        public string CampusName { get; set; }
    }
}

eCert/Controllers/SuperAdminController.cs
using eCert.Models.ViewModel;
using eCert.Services;
using eCert.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static eCert.Utilities.Constants;

namespace eCert.Controllers
{
    public class SuperAdminController : Controller
    {
        private readonly SuperAdminServices _superAdminServices;
        private readonly UserServices _userServices;
        private readonly FileServices _fileServices;
        private readonly AdminServices _adminServices;
        public SuperAdminController()
        {
            _superAdminServices = new SuperAdminServices();
            _userServices = new UserServices();
            _fileServices = new FileServices();
            _adminServices = new AdminServices();

        }
        // GET: SuperAdmin
        public ActionResult Index()
        {
            string currentRoleName = "";
            if (Session["RoleName"] != null)
            {
                currentRoleName = Session["RoleName"].ToString();
            }
            if (currentRoleName == Utilities.Constants.Role.SUPER_ADMIN)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Authentication");
            }
        }
        public ActionResult ManageSignature()
        {
            string currentRoleName = "";
            if (Session["RoleName"] != null)
            {
                currentRoleName = Session["RoleName"].ToString();
            }
            if (currentRoleName == Utilities.Constants.Role.SUPER_ADMIN)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Authentication");
            }
        }
        public ActionResult LoadListOfSignature(int pageSize = 8, int pageNumber = 1)
        {
            //get list user academic service
            ViewBag.Pagination = _superAdminServices.GetSignaturePagination(pageSize, pageNumber);
            if (ViewBag.Pagination.PagingData.Count == 0)
            {
                ViewBag.OverflowHidden = "overflow-hidden";
            }
            else
            {
                ViewBag.OverflowHidden = String.Empty;
            }
            return PartialView();
        }
        public ActionResult AddAcaService()
        {
            string currentRoleName = "";
            if (Session["RoleName"] != null)
            {
                currentRoleName = Session["RoleName"].ToString();
            }
            if (currentRoleName == Utilities.Constants.Role.SUPER_ADMIN)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Authentication");
            }
        }

        public ActionResult AddAdmin()
        {
            string currentRoleName = "";
            if (Session["RoleName"] != null)
            {
                currentRoleName = Session["RoleName"].ToString();
            }
            if (currentRoleName == Utilities.Constants.Role.SUPER_ADMIN)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Authentication");
            }
        }
        public ActionResult ManageCampus()
        {
            return View();
        }
        public ActionResult AddCampus()
        {
            string currentRoleName = "";
            if (Session["RoleName"] != null)
            {
                currentRoleName = Session["RoleName"].ToString();
            }
            if (currentRoleName == Utilities.Constants.Role.SUPER_ADMIN)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Authentication");
            }
        }
        [HttpPost]
        public ActionResult AddCampus(CampusViewModel campusViewModel)
        {
            if (ModelState.IsValid)
            {
                int count = _superAdminServices.GetCountCampusByName(campusViewModel.CampusName.ToLower(), campusViewModel.EducationSystemId);
                if (count != 0)
                {
                    ViewBag.Msg = "This campus has already existed. Please input other name.";
                    return View();
                }

                //Add to database education system & campus
                _superAdminServices.AddCampus(campusViewModel);
                TempData["Msg"] = "Create campus successfully.";
                return View();
            }
            else
            {
                return View();
            }
        }
        [HttpPost]
        public ActionResult AddAcaService(StaffViewModel userViewModel)
        {
            if (ModelState.IsValid)
            {
                string academicEmail = userViewModel.AcademicEmail;
                //check exist email in DB
                UserViewModel user = _userServices.GetUserByAcademicEmail(academicEmail);
                if (user != null && user.Role.RoleName != Utilities.Constants.Role.FPT_UNIVERSITY_ACADEMIC)
                {
                    //ModelState.AddModelError("ErrorMessage", "Invalid. This email has been existed.");
                    ViewBag.Msg = "Invalid. This email has been existed.";
                    return View();
                }

                //check if choosen campus already has academic service
                UserViewModel userByCampusId = _userServices.GetAcaServiceByCampusIdAndAcaEmail(userViewModel.CampusId, academicEmail);
                UserViewModel userActiveByCampusId = _userServices.GetActiveAcaServiceByCampusId(userViewModel.CampusId);
                //case email existed in DB
                if (userByCampusId != null)
                {
                    if (userByCampusId.AcademicEmail.Equals(userViewModel.AcademicEmail))
                    {
                        ViewBag.Msg = "Invalid. This account was responsible for this campus.";
                        return View();
                    }
                }
                if (userActiveByCampusId != null)
                {
                    ViewBag.Msg = "Invalid. This campus has already had an active academic service account.";
                    return View();
                }
                //}
                else
                {
                    UserViewModel addAcademicService = new UserViewModel()
                    {
                        UserId = (user != null) ? user.UserId : -1,
                        PhoneNumber = userViewModel.PhoneNumber,
                        AcademicEmail = academicEmail,
                        IsVerifyMail = true
                    };
                    _superAdminServices.AddAcademicSerivce(addAcademicService, userViewModel.CampusId);

                    //send email

                    TempData["Msg"] = "Create academic service user successfully";
                    TempData["Tab"] = 2;
                    return View();
                }
            }
            else
            {
                return View();
            }

        }

        [HttpPost]
        public ActionResult AddAdmin(StaffViewModel userViewModel)
        {
            if (ModelState.IsValid)
            {
                string academicEmail = userViewModel.AcademicEmail;
                //check exist email in DB
                UserViewModel user = _userServices.GetUserByAcademicEmail(academicEmail);
                if (user != null && user.Role.RoleName != Utilities.Constants.Role.ADMIN)
                {
                    //ModelState.AddModelError("ErrorMessage", "Invalid. This email has been existed.");
                    ViewBag.Msg = "Invalid. This email has been existed.";
                    return View();
                }
                //check if choosen campus already has academic service
                UserViewModel userByCampusId = _userServices.GetAdminByCampusIdAndAcaEmail(userViewModel.CampusId, academicEmail);
                UserViewModel userActiveByCampusId = _userServices.GetActiveAdminByCampusId(userViewModel.CampusId);
                //case email existed in DB
                if (userByCampusId != null)
                {
                    if (userByCampusId.AcademicEmail.Equals(userViewModel.AcademicEmail))
                    {
                        ViewBag.Msg = "Invalid. This account was responsible for this campus.";
                        return View();
                    }
                }
                if (userActiveByCampusId != null)
                {
                    ViewBag.Msg = "Invalid. This campus has already had an active admin account.";
                    return View();
                }
                else
                {
                    UserViewModel addAcademicService = new UserViewModel()
                    {
                        UserId = (user != null) ? user.UserId : -1,
                        PhoneNumber = userViewModel.PhoneNumber,
                        AcademicEmail = academicEmail,
                        IsVerifyMail = true
                    };
                    _superAdminServices.AddAdminSerivce(addAcademicService, userViewModel.CampusId);

                    //send email

                    TempData["Msg"] = "Create admin user successfully.";
                    TempData["Tab"] = 1;
                    return View();
                }
            }
            else
            {
                return View();
            }

        }
        public ActionResult LoadAllAdmin(int pageSize = 8, int pageNumber = 1)
        {
            //get list user academic service
            ViewBag.Pagination = _superAdminServices.GetAdminPagination(pageSize, pageNumber);
            if (ViewBag.Pagination.PagingData.Count == 0)
            {
                ViewBag.OverflowHidden = "overflow-hidden";
            }
            else

eCert/Views/SuperAdmin/AddAcaService.cshtml
@model eCert.Models.ViewModel.StaffViewModel
@{
    Layout = "~/Views/Shared/_LayoutSuperAdmin.cshtml";
}
<!--Jquery-->
<script src="~/Scripts/jquery-3.5.1.min.js"></script>
<script src="~/Scripts/jquery-3.5.1.js"></script>
<!--Custom js-->
<script src="~/Assets/js/custom/import.js"></script>
<!--custom css-->
<link rel="stylesheet"
      type="text/css"
      href="/assets/css/custom/share.css" />

@using (Html.BeginForm("AddAcaService", "SuperAdmin", FormMethod.Post, new { enctype = "multipart/form-data", @class = "addForm" }))
{
    <div class="row justify-content-center">
        <div class="card col-12 col-lg-6">
            <div class="card-body">
                <div class="d-flex justify-content-between">
                    <h3 class="mb-4">Create Academic Service Account</h3>
                    <div class="">
                        <a class="btn btn-download" href="/SuperAdmin/ManageAccount">
                            Back to Manage user
                        </a>
                    </div>
                </div>

                <div class="">


                    <div class="row col-12 px-0">
                        <div class="form-group col-12 col-lg-6 required">
                            <label class="control-label">Email (include @@fpt.edu.vn):</label>
                            @Html.TextBoxFor(model => model.AcademicEmail, new { @type = "email", @class = "form-control mb-1", placeholder = "Email" })
                            @Html.ValidationMessageFor(model => model.AcademicEmail, "", new { @class = "text-danger mt-1" })
                        </div>
                        <div class="form-group col-12 col-lg-6 pr-0 required">
                            <label class="control-label">Phone number:</label>
                            @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control mb-1", placeholder = "Phone number" } })
                            @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="row col-12 px-0">
                        <div class="form-group col-12 col-lg-6 required">
                            <label class="control-label">Education System: </label>
                            <select class="form-control" id="EducationSystemId" name="EducationSystemId">
                                <option selected disabled>Select Education System</option>
                            </select>
                            <div class="mt-2">
                                @Html.ValidationMessageFor(model => model.EducationSystemId, "", new { @class = "text-danger mb-1" })
                            </div>
                        </div>

                        <div id="campus-select" class="form-group col-12 col-lg-6 pr-0 required">
                            <label class="control-label">Campus: </label>
                            <select class="form-control" id="CampusId" name="CampusId">
                                <option selected disabled>Select Campus</option>
                            </select>
                            <div class="mt-2">
                                @Html.ValidationMessageFor(model => model.CampusId, "", new { @class = "text-danger mb-1" })
                            </div>
                        </div>
                    </div>
                    <div class="row col-12 px-0 justify-content-end">

                        <button type="submit" class="btn btn-primary">
                            Create
                        </button>
                    </div>
                    @Html.ValidationMessageFor(model => model.ErrorMessage, "", new { @class = "text-danger" })
                </div>


            </div>
        </div>
    </div>

}
@Html.Partial("_AlertDialog")
@if (TempData["Msg"] != null)
{
    <script type="text/javascript">
       $(document).ready(function () {
           var data = '@TempData["Msg"]';
           $.NotificationApp.send("Message", data, "top-center", "Background color", "Icon");
          });
    </script>
}
else if (ViewBag.Msg != null)
{
    <script type="text/javascript">
       $(document).ready(function () {
           var data = '@ViewBag.Msg';
           $('#alertModal').modal('show');
           $('#confirmTitle').html('Alert');
           $('.modal-body').html(data);
          });
    </script>
}

eCert/Views/SuperAdmin/AddAdmin.cshtml
@model eCert.Models.ViewModel.StaffViewModel
@{
    Layout = "~/Views/Shared/_LayoutSuperAdmin.cshtml";
}
<!--Jquery-->
<script src="~/Scripts/jquery-3.5.1.min.js"></script>
<script src="~/Scripts/jquery-3.5.1.js"></script>
<!--Custom js-->
<script src="~/Assets/js/custom/import.js"></script>
<!--custom css-->
<link rel="stylesheet"
      type="text/css"
      href="/assets/css/custom/detailCertificate.css" />
<link rel="stylesheet"
      type="text/css"
      href="~/assets/css/custom/share.css" />
@using (Html.BeginForm("AddAdmin", "SuperAdmin", FormMethod.Post, new { enctype = "multipart/form-data", @class = "addForm" }))
{
    <div class="row justify-content-center">
        <div class="card col-12 col-lg-6">
            <div class="card-body">
                <div class="d-flex justify-content-between">
                    <h3 class="mb-4">Create Admin Account</h3>
                    <div class="">
                        <a class="btn btn-download" href="/SuperAdmin/ManageAccount">
                            Back to Manage user
                        </a>
                    </div>
                </div>

                <div class="">
                    <div class="row col-12 px-0">
                        <div class="form-group col-12 col-lg-6 required">
                            <label class="control-label">Email (include @@fpt.edu.vn):</label>
                            @Html.TextBoxFor(model => model.AcademicEmail, new { @type = "email", @class = "form-control mb-1", placeholder = "Email" })
                            @Html.ValidationMessageFor(model => model.AcademicEmail, "", new { @class = "text-danger mt-1" })
                        </div>
                        <div class="form-group col-12 col-lg-6 pr-0 required">
                            <label class="control-label">Phone number:</label>
                            @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control mb-1", placeholder = "Phone number" } })
                            @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="row col-12 px-0">
                        <div class="form-group col-12 col-lg-6 required">
                            <label class="control-label">Education System: </label>
                            <select class="form-control" id="EducationSystemId" name="EducationSystemId">
                                <option selected disabled>Select Education System</option>
                            </select>
                            <div class="mt-2">
                                @Html.ValidationMessageFor(model => model.EducationSystemId, "", new { @class = "text-danger mb-1" })
                            </div>
                        </div>

                        <div id="campus-select" class="form-group col-12 col-lg-6 pr-0 required">
                            <label class="control-label">Campus: </label>
                            <select class="form-control" id="CampusId" name="CampusId">
                                <option selected disabled>Select Campus</option>
                            </select>
                            <div class="mt-2">
                                @Html.ValidationMessageFor(model => model.CampusId, "", new { @class = "text-danger mb-1" })
                            </div>
                        </div>
                    </div>
                    <div class="row col-12 px-0 justify-content-end">

                        <button type="submit" class="btn btn-primary">
                            Create
                        </button>
                    </div>
                    @Html.ValidationMessageFor(model => model.ErrorMessage, "", new { @class = "text-danger" })
                </div>


            </div>
        </div>
    </div>

}

@Html.Partial("_AlertDialog")

@if (TempData["Msg"] != null)
{
    <script type="text/javascript">
       $(document).ready(function () {
           var data = '@TempData["Msg"]';
           $.NotificationApp.send("Message", data, "top-center", "Background color", "Icon");
          });
    </script>
}
else if (ViewBag.Msg != null)
{
    <script type="text/javascript">
       $(document).ready(function () {
           var data = '@ViewBag.Msg';
           $('#alertModal').modal('show');
           $('#confirmTitle').html('Alert');
           $('.modal-body').html(data);
          });
    </script>
}

eCert/Views/SuperAdmin/AddCampus.cshtml
@model eCert.Models.ViewModel.CampusViewModel
@{
    Layout = "~/Views/Shared/_LayoutSuperAdmin.cshtml";
}
<script src="/assets/js/vendor/jquery-3.5.1.min.js"></script>
<link rel="stylesheet"
      type="text/css"
      href="~/assets/css/custom/share.css" />
<!--Custom js-->
<script src="~/Assets/js/custom/import.js"></script>
<div class="row">
    <div class="col-12 d-flex justify-content-center">
        <div class="card col-12 col-lg-6">
            <div class="card-body">
                <div class="d-flex justify-content-between">
                    <h3 class="page-title">Add Campus</h3>
                    <div class="">
                        <a class="btn btn-download d-none d-sm-block" href="/SuperAdmin/ManageCampus">
                            Back to Manage Campus
                        </a>
                        <a class="btn btn-download d-block d-sm-none" href="/SuperAdmin/ManageCampus">
                            Back
                        </a>
                    </div>
                </div>

                <div class="tab-pane show active card-body px-0 pt-0 mt-3" id="input-types-preview">
                    @using (Html.BeginForm("AddCampus", "SuperAdmin", FormMethod.Post, new { enctype = "multipart/form-data", id = "addCampus" }))
                    {
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="form-group required">
                                    <label class="control-label">Education System: </label>
                                    <select class="form-control" id="EducationSystemId" name="EducationSystemId">
                                        <option selected disabled>Select Education System</option>
                                    </select>
                                    <div class="mt-2">
                                        @Html.ValidationMessageFor(model => model.EducationSystemId, "", new { @class = "text-danger mb-1" })
                                    </div>

                                </div>
                            </div> <!-- end col -->

                            <div class="col-lg-6">
                                <div class="form-group required">
                                    <label class="control-label">Campus Name</label>
                                    @Html.EditorFor(model => model.CampusName, new { htmlAttributes = new { @class = "form-control", placeholder = "Campus name" } })
                                    <div class="mt-2">
                                        @Html.ValidationMessageFor(model => model.CampusName, "", new { @class = "text-danger mb-1" })
                                    </div>
                                </div>
                            </div>
                            <!-- end col -->
                        </div><!-- end row-->
                        <div class="d-flex justify-content-end">
                            <button type="submit" class="btn btn-primary">Add</button>
                        </div>

                    }
                </div> <!-- end preview-->
            </div>
        </div>

    </div>
</div>
@Html.Partial("_AlertDialog")
@if (TempData["Msg"] != null)
{
    <script type="text/javascript">
       $(document).ready(function () {
           var data = '@TempData["Msg"]';
           $.NotificationApp.send("Message", data, "top-center", "Background color", "Icon");
          });
    </script>
}
else if (ViewBag.Msg != null)
{
    <script type="text/javascript">
       $(document).ready(function () {
           var data = '@ViewBag.Msg';
           $('#alertModal').modal('show');
           $('#confirmTitle').html('Alert');
           $('.modal-body').html(data);
          });
    </script>
}

eCert/Views/SuperAdmin/AddEducation.cshtml
@model eCert.Models.ViewModel.EducationSystemViewModel
@{
    ViewBag.Title = null;
    Layout = "~/Views/Shared/_LayoutSuperAdmin.cshtml";
}

<!--Jquery-->
<script src="~/Scripts/jquery-3.5.1.min.js"></script>
<script src="~/Scripts/jquery-3.5.1.js"></script>
<!--Custom js-->
<script src="~/Assets/js/custom/addEducation.js"></script>
<!--custom css-->
<link rel="stylesheet"
      type="text/css"
      href="~/assets/css/custom/share.css" />
@*<div class="page-title-box">
        <div class="page-title-right">
            <ol class="breadcrumb m-0">
                <li class="breadcrumb-item">
                    <a href="javascript: void(0);">Home</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="javascript: void(0);">SuperAdmin</a>
                </li>
                <li class="breadcrumb-item active">Add Education System</li>
            </ol>
        </div>

    </div>*@

<div class="row">
    <div class="col-12 d-flex justify-content-center">
        <div class="card col-12 col-lg-6">
            <div class="card-body">
                <div class="d-flex justify-content-between">
                    <h3 class="page-title">Add Education System</h3>
                    <div class="">
                        <a class="btn btn-download d-none d-sm-block" href="/SuperAdmin/ManageEducation">
                            Back to Manage Education System
                        </a>
                        <a class="btn btn-download d-block d-sm-none" href="/SuperAdmin/ManageEducation">
                            Back
                        </a>
                    </div>
                </div>
                <p class="text-muted font-14">
                    *Attention: Please upload image with extension .jpg, .jpeg, .png and size under 5 MB.
                </p>
                <div class="tab-pane show active card-body px-0 pt-0" id="input-types-preview">
                    @using (Html.BeginForm("AddEducation", "SuperAdmin", FormMethod.Post, new { enctype = "multipart/form-data", id = "addEducation" }))
                    {
                        <div class="row">
                            <div class="col-lg-6">
                                <div>
                                    <div class="form-group required">
                                        <label class="control-label" for="simpleinput">Name</label>
                                        @Html.TextBoxFor(m => m.EducationName, new { @class = "form-control", placeholder = "Education system name" })
                                    </div>
                                    <div class="my-2">
                                        @Html.ValidationMessageFor(model => model.EducationName, "", new { @class = "text-danger mb-1" })
                                    </div>


                                </div>
                            </div> <!-- end col -->
                            @*<div class="col-lg-6">
                                    <div class="input_fields_wrap">
                                        <div class="form-group required">
                                            <label class="control-label" for="simpleinput">Campus</label>
                                            <div class="d-flex align-items-center">
                                                @Html.TextBox("CampusNames", "", new { @class = "form-control", placeholder = "Campus name" })
                                                <button type="button" class="btn btn-primary ml-2 add_field_button">+</button>
                                            </div>

                                        </div>
                                    </div>
                                    <div class="my-2">
                                        @Html.ValidationMessageFor(model => model.Campuses, "", new { @class = "text-danger mb-1" })
                                    </div>
                                </div>*@
                            <div class="col-lg-6">
                                <div class="form-group required">
                                    <label class="control-label">Logo Image</label>

                                    <div class="input-group">
                                        <div class="custom-file col-12">
                                            @Html.TextBox("LogoImageFile", "", new { type = "file", @class = "custom-file-input", accept = ".jpg,.png,.jpeg", multiple = "multiple" })
                                            <label class="custom-file-label" for="inputGroupFile04">Choose file</label>
                                        </div>


                                    </div>
                                    <div class="my-2">
                                        @Html.ValidationMessageFor(model => model.LogoImageFile, "", new { @class = "text-danger mb-1" })
                                    </div>
                                </div>
                            </div>
                            <!-- end col -->
                        </div><!-- end row-->
                        <div class="d-flex justify-content-end">
                            <button type="submit" class="btn btn-primary">Add</button>
                        </div>

                    }
                </div> <!-- end preview-->
            </div>
        </div>

    </div>
</div>
@Html.Partial("_AlertDialog")

@if (TempData["Msg"] != null)
{
    <script type="text/javascript">
       $(document).ready(function () {
           var data = '@TempData["Msg"]';
           $.NotificationApp.send("Message", data, "top-center", "Background color", "Icon");
          });
    </script>
}
else if (ViewBag.Msg != null)
{
    <script type="text/javascript">
       $(document).ready(function () {
           var data = '@ViewBag.Msg';
           $('#alertModal').modal('show');
           $('#confirmTitle').html('Alert');
           $('.modal-body').html(data);
          });
    </script>
}

eCert/Views/SuperAdmin/ManageCampus.cshtml
<script src="/assets/js/vendor/jquery-3.5.1.min.js"></script>
<!--Custom js-->
<script src="~/Assets/js/custom/manageCampus.js"></script>
<link rel="stylesheet"
      type="text/css"
      href="~/assets/css/custom/share.css" />
@{
    Layout = "~/Views/Shared/_LayoutSuperAdmin.cshtml";
}

<div class="row justify-content-center">
    <div class="card col-12 col-lg-6">
        <div class="card-body">
            <div class="d-flex justify-content-between">
                <h3 class="mb-3">Manage Campus</h3>
                <div class="">
                    <a class="btn btn-download" href="/SuperAdmin">
                        Back to Home
                    </a>
                </div>
            </div>
            <div class="btn-add">
                <a href="/SuperAdmin/AddCampus" class="btn btn-primary mb-3">Add Campus</a>
            </div>
            <div class="form-group d-flex pl-0">
                <div>
                    <label class="control-label mt-1 pl-0">Education System: </label>
                </div>
                <div class="ml-2">
                    <select class="form-control" id="EducationSystemId" name="EducationSystemId">
                        <option selected disabled>Select Education System</option>
                    </select>
                </div>
                
            </div>

            <div class="listCampus">
            </div>
        </div>
    </div>
</div>

@Html.Partial("_AlertDialog")