eCert/Controllers/AcademicServiceController.cs
using eCert.Models.ViewModel;
using eCert.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eCert.Controllers
{
    public class AcademicServiceController : Controller
    {
        private readonly CertificateServices _certificateServices;
        private readonly UserServices _userServices;
        
        public AcademicServiceController()
        {
            _certificateServices = new CertificateServices();
            _userServices = new UserServices();
        }
        // GET: AcademicService
        public ActionResult Index()
        {
            if (Session["RoleName"].ToString() == Utilities.Constants.Role.FPT_UNIVERSITY_ACADEMIC)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Authentication");
            }
        }

        public ActionResult LoadAllReport(int pageSize = 8, int pageNumber = 1)
        {
            string academicEmail = Session["AcademicEmail"].ToString();
            UserViewModel userViewModel = _userServices.GetUserByAcademicEmail(academicEmail);
            if(userViewModel != null)
            {
                ViewBag.Pagination = _certificateServices.GetReportByUserIdPagination(userViewModel.UserId, pageSize, pageNumber);
                if (ViewBag.Pagination.PagingData.Count == 0)
                {
                    ViewBag.OverflowHidden = "overflow-hidden";
                }
                else
                {
                    ViewBag.OverflowHidden = String.Empty;
                }
            }
            
            return PartialView();
        }
        public ActionResult DetailReport(int reportId)
        {
            string currentRoleName = "";
            if (Session["RoleName"] != null)
            {
                currentRoleName = Session["RoleName"].ToString();
            }
            if (currentRoleName == Utilities.Constants.Role.FPT_UNIVERSITY_ACADEMIC)
            {
                ReportViewModel report = _certificateServices.GetReportByReportId(reportId);
                if (report != null)
                {
                    UserViewModel userViewModel = _userServices.GetUserByUserId(report.UserId);
                    ViewBag.User = userViewModel;
                }
                else
                {
                    ViewBag.ErrorMsg = "This report does not exist.";
                }
                return View(report);
            }
            else
            {
                return RedirectToAction("Index", "Authentication");
            }
        }

        public JsonResult GetStatusByReportId(int reportId)
        {
            ReportViewModel report = _certificateServices.GetReportByReportId(reportId);
            return Json(report.Status, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult DetailReport(ReportViewModel reportViewModel)
        {
            ReportViewModel report = _certificateServices.GetReportByReportId(reportViewModel.ReportId);
            if(report != null)
            {
                try
                {
                    UserViewModel userViewModel = _userServices.GetUserByUserId(report.UserId);
                    ViewBag.User = userViewModel;
                    report.Status = reportViewModel.Status;
                    _certificateServices.UpdateReport(report);
                    TempData["Msg"] = "Update status report successfully.";
                }catch(Exception e)
                {
                    ViewBag.Msg = "Update fail.";
                }
                
            }
            else
            {
                ViewBag.ErrorMsg = "This report does not exist.";
            }
           
            return View(report);
        }


    }
}

eCert/Views/AcademicService/DetailReport.cshtml
<script src="/assets/js/vendor/jquery-3.5.1.min.js"></script>
@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@model eCert.Models.ViewModel.ReportViewModel
@using eCert.Models.ViewModel
@using eCert.Utilities

<script src="~/assets/js/custom/DetailReport.js"></script>
<!--custom css-->
<link rel="stylesheet"
      type="text/css"
      href="~/assets/css/custom/detailReport.css" />
<link rel="stylesheet"
      type="text/css"
      href="~/assets/css/custom/academicReport.css" />
<link rel="stylesheet"
      type="text/css"
      href="~/assets/css/custom/share.css" />



<div class="container-fluid">

    <div class="d-flex justify-content-between">
        <h3 class="page-title">Detail Report</h3>
        <div class="">
            <a class="btn btn-download" href="/AcademicService/">
                Back to Home
            </a>
        </div>
    </div>
    @if (ViewBag.ErrorMsg != null)
    {
        <p>This report does not exist</p>
    }
    else
    {
        <div class="shadow p-3 mb-5 mt-2 bg-white rounded">
            <!-- REPORT TITLE-->
            <div class="row">
                <div class="col-12">
                    <h4>@Model.Title</h4>
                </div>
            </div>
            <!-- REPORT CONTENT-->
            <div class="d-flex justify-content-end bd-highlight pt-3 mt-3 my-border">
                <div class="mr-auto bd-highlight">
                    <strong>@Model.Fullname </strong><br> From: @ViewBag.User.AcademicEmail
                </div>
                <div class=" pr-2 bd-highlight">
                    <span>Current status:</span>
                    @if (Model.Status.Equals(Constants.StatusReport.PENDING))
                    {
                        <span class="badge badge-warning ">@Model.Status</span>
                    }
                    else if (Model.Status.Equals(Constants.StatusReport.UPDATED))
                    {
                        <span class="badge badge-success ">@Model.Status</span>
                    }
                    else if (Model.Status.Equals(Constants.StatusReport.REJECTED))
                    {
                        <span class="badge badge-danger ">@Model.Status</span>
                    }

                </div>
                <div class="bd-highlight">
                    <p>@Model.CreateTime</p>
                </div>
            </div>

            <div class="mt-2">

                @Model.ReportContent

            </div>
            <!-- UPDATE STATUS-->
            <div class="bd-highlight pt-3 mt-5 my-border">
                <strong>Update Status Report</strong>
                @using (Html.BeginForm("DetailReport", "AcademicService", FormMethod.Post, new { enctype = "multipart/form-data", id = "updateStatus" }))
                {
                    @Html.HiddenFor(m => m.ReportId)
                    <div class="form-check form-check-inline">
                        @Html.RadioButtonFor(m => m.Status, "Pending")
                        <label class="form-check-label ml-1" for="inlineRadio1">Pending</label>
                    </div>
                    <div class="form-check form-check-inline">
                        @Html.RadioButtonFor(m => m.Status, "Updated")
                        <label class="form-check-label ml-1" for="inlineRadio2">Updated</label>
                    </div>
                    <div class="form-check form-check-inline">
                        @Html.RadioButtonFor(m => m.Status, "Rejected")
                        <label class="form-check-label ml-1" for="inlineRadio3">Rejected</label>
                    </div>
                    <button type="submit" class="btn btn-primary">Update</button>
                }

            </div>
        </div>
    }

</div>
@Html.Partial("_AlertDialog")

@if (TempData["Msg"] != null)
{
    <script type="text/javascript">
       $(document).ready(function () {
           var data = '@TempData["Msg"]';
           $.NotificationApp.send("Message", data, "top-center", "Background color", "Icon");
          });
    </script>
}
else if (ViewBag.Msg != null)
{
    <script type="text/javascript">
       $(document).ready(function () {
           var data = '@ViewBag.Msg';
           $('#alertModal').modal('show');
           $('#confirmTitle').html('Alert');
           $('.modal-body').html(data);
          });
    </script>
}

eCert/Views/AcademicService/EditReport.cshtml
@model eCert.Models.ViewModel.ReportViewModel
<!--Custom css-->
<link href="~/assets/CSS/custom/addReport.css"
      rel="stylesheet"
      type="text/css" />

@using (Html.BeginForm("AddReport", "Certificate", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="row">
        <div class="row col-12 justify-content-center">
            <div class="card col-12">
                <div class="card-body">
                    <h3 class="mb-4">Report detail</h3>
                    @*@Html.HiddenFor(model => model.ReportId)
                    <div class="form-group mb-3">
                        <label for="simpleinput">Title: </label>
                        @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", placeholder = "Your certificate name", @readonly = "readonly" } })
                    </div>
                    <div class="form-group">
                        <label for="simpleinput">Certificate Name: </label>
                        @Html.EditorFor(model => model.CertificateName, new { htmlAttributes = new { @class = "form-control", placeholder = "Your certificate name", @readonly = "readonly" } })
                    </div>
                    <div class="form-group">
                        <label for="example-textarea">Student's roll number: </label>
                        @Html.EditorFor(model => model.RollNumber, new { htmlAttributes = new { @class = "form-control", placeholder = "Your certificate name", @readonly = "readonly" } })
                    </div>
                    <div class="form-group">
                        <label for="example-textarea">Description: </label>
                        @Html.TextAreaFor(model => model.ReportContent, new { htmlAttributes = new { @class = "form-control", placeholder = "Your certificate name", @readonly = "readonly" } })
                    </div>
                    <div>
                        <button type="submit" class="btn btn-primary">
                            Update
                        </button>
                    </div>*@
                    <div>
                        Missing Issue Date
                    </div>
                </div>
            </div>
        </div>
    </div>
}


@*@Html.Partial("_NotificationDialog")*@

eCert/Views/AcademicService/Index.cshtml
@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<script src="/assets/js/vendor/jquery-3.5.1.min.js"></script>
<script src="~/assets/js/custom/listReportOfAcaService.js"></script>
<link href="~/assets/css/custom/academicReport.css"
      rel="stylesheet"
      type="text/css" />

<div class="content">
    <div class="title">
        <h3>Report</h3>
    </div>
    <div class="shadow p-3 mb-5 bg-white rounded">
       <div class="listAllReport">

       </div>
    </div>
    
</div>